# Generated by Django 5.0.14 on 2025-12-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('setor', models.CharField(choices=[('Diretoria', 'Diretoria'), ('Financeiro', 'Financeiro'), ('Juridico', 'Juridico'), ('Contabilidade', 'Contabilidade'), ('RH', 'RH'), ('Comercial', 'Comercial'), ('Operacional', 'Operacional'), ('Gate', 'Gate'), ('Manutencao', 'Manutencao')], max_length=50)),
                ('ramal', models.CharField(max_length=10)),
                ('solicitante', models.CharField(max_length=100)),
                ('tecnico_responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('prioridade', models.CharField(blank=True, max_length=20, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
