# Generated by Django 5.0.14 on 2025-12-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='chamados/'),
        ),
    ]
