# Generated by Django 6.0.1 on 2026-02-07 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_chamado_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_reserva',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='sala_selecionada',
            field=models.CharField(choices=[('nenhuma', 'Nenhuma (Apenas chamado)'), ('Sala 01', 'Sala de Reunião 01'), ('Sala 02', 'Sala de Reunião 02')], default='nenhuma', max_length=20),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição/Pauta'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta'), ('Urgência', 'Urgência')], default='Baixa', max_length=20),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='ramal',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='setor',
            field=models.CharField(choices=[('Diretoria', 'Diretoria'), ('Juridico', 'Jurídico'), ('Financeiro', 'Financeiro'), ('Compras', 'Compras'), ('Contabilidade', 'Contabilidade'), ('Capital Humano', 'Capital Humano'), ('Comercial', 'Comercial'), ('Operacional/Gate', 'Operacional/Gate'), ('Manutencao/Almoxarifado', 'Manutenção/Almoxarifado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Andamento', 'Em Andamento'), ('Concluido', 'Concluido')], default='Pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='O que foi feito/Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='chamados.chamado')),
            ],
            options={
                'verbose_name': 'Histórico de Atendimento',
            },
        ),
    ]
